#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

if [ ! -x /sbin/vgcreate ]; then
	exit 0
fi

if [ ! -x /sbin/lvcreate ]; then
	exit 0
fi

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/vgcreate
copy_exec /sbin/lvcreate
